service: example-apis2

provider:
  name: aws
  memorySize: 512
  region: us-west-1
  apiGateway:
    restApiId: ${env:APIGWID} #  API Gateway to add this api to
    restApiRootResourceId: ${env:RESOURCEID}
functions:
  example1:
    handler: index.handler
    layers:
      - arn:aws:lambda:us-west-1:730341620930:layer:example-layer:1
    events:
      - http:
          path: api2
          method: get
